name: SimpleVoiceChatMusic
version: '3.1.0'
main: dev.klash.simpleVoiceChatMusic.SimpleVoiceChatMusic
api-version: '1.21'
authors: [ GavinGoGaming, MrTron ]
depend: [ voicechat ]
description: A port of the SimpleVoiceChatMusic fabric mod by ItzDerock to PaperMC. Which has now been forked from GavinGoGaming to up-to-date standards and adds spotify search!
commands:
  music:
    description: Play music in voice chat.
    usage: /music <...>
    permission: simplevoicechatmusic.music
    aliases: [ svcmusic ]
  music_register_service:
    description: Register SVCM plugin service.
permissions:
  simplevoicechatmusic.music:
    description: Allows the player to play music in voice chat.
    default: true